### ISSUE TITLE
question: How's it different from PostHTML?

### ISSUE THREAD

**Issue by iamale** [wooorm/rehype#8]
Subj. See https://github.com/posthtml/posthtml.

**Comment by wooorm** [comment]
That’s a good question. We talked about this a while back (https://github.com/syntax-tree/hast/issues/3).

There’s four main differences:

1. The syntax tree is different: [hast](https://github.com/syntax-tree/hast) is very convenient to work with. hast is based on [unist](https://github.com/syntax-tree/unist), which means there’s many tools to work with the syntax tree
2. The API is different. rehype is based on [unified](https://github.com/unifiedjs/unified), which is also used for markdown in [remark](https://github.com/wooorm/remark), and natural language, in [retext](https://github.com/wooorm/retext). I think unified is really useful. There’s also “bridges” to transform to remark or retext, keeping positional info intact, which means that linting messages are kept intact.
3. PostHTML uses htmlparser2 (by default?), rehype uses parse5 (by default)
4. The ecosystem is different: although there aren’t many plugins for rehype, the plugins that exist are custom made for rehype. PostHTML seems to often stringify to HTML, post that to an API or CLI, and parse the resulting HTML. On the other hand, take `remark-format` and `rehype-minify`, both are custom made for rehype, *very good*, work fast as they don’t need to stringify/parse in between, and keep position information intact (*very* useful for linting, source maps, etc).

...possible more though...

Does that help?

**Comment by iamale** [comment]
Definitely. Thanks!
